spring.application.name=Car Rental Management System


server.port= 8080

# PostgreSQL Database
spring.datasource.username=postgres
spring.datasource.password=Fiacre.1
spring.datasource.url=jdbc:postgresql://localhost:5432/car_rental_system
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework.web=DEBUG
logging.level.com.carrental=DEBUG